name: elias_voice_assistant
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.4
  - scipy=1.11.4
  - pillow=10.3.0
  - pip
  - pip:
    - torch==2.7.0
    - torchaudio==2.7.0
    - torchvision==0.22.0
    - PyAudio==0.2.14
    - faster-whisper==1.1.1
    - soundfile==0.12.1
    - langid==1.1.6
    - librosa==0.10.2.post1
    - transformers==4.51.0
    - pydantic==2.7.4
    - pydub==0.25.1
    - openai==1.68.2
    - anthropic==0.49.0
    - textblob==0.18.0.post0
    - python-dotenv==1.0.1
    - requests==2.32.4
    - fastapi==0.115.11
    - uvicorn==0.30.1
    - aiohttp==3.12.14
    - spacy==3.7.5
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - coqui-tts==0.26.0
    - aiortc==1.10.1
    - av==11.0.0
    - httpx==0.28.1
    - websockets==15.0.1
